os: linux
dist: xenial
language: python
python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "2.7"
  - "nightly"
  - "pypy3.5-6.0"
env: TOXENV=py,codecov

matrix:
  include:
    - env: TOXENV=stylecheck,docs-html
    - os: osx
      language: generic
      env: TOXENV=py3,codecov
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
          - $HOME/Library/Caches/pip
  allow_failures:
    - python: nightly
    - python: pypy3.5-6.0
    - os: osx
  fast_finish: true

install:
  - pip install -U tox

script:
  - tox --skip-missing-interpreters false

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

branches:
  only:
    - master
    - /^\d+(\.\d+)*(\.x)?$/

notifications:
  email: false
